import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';
import { CSSReset, ChakraProvider, ColorModeScript } from '@chakra-ui/react';
import { AppProps } from 'next/app';
import '@/styles/cm-dark.css';
import '@/styles/cm-light.css';
import '@/styles/globals.css';
import theme from '../theme';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={cn(
					'min-h-screen bg-background  font-sans antialiased',
					fontSans.variable
				)}
			>
				<ChakraProvider>
					<ColorModeScript />
					<CSSReset />
					{children}
				</ChakraProvider>
			</body>
		</html>
	);
}
